from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import io

def set_cell_bg(cell, hex_color):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), hex_color)
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:val"), "clear")
    tcPr.append(shd)

def generate_mom_docx(
    mom_data: dict,
    meeting_title: str
) -> bytes:
    doc = Document()

    for section in doc.sections:
        section.left_margin   = Inches(1)
        section.right_margin  = Inches(1)
        section.top_margin    = Inches(1)
        section.bottom_margin = Inches(1)

    # Title
    title = doc.add_heading("MINUTES OF MEETING", 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(13, 43, 110)
        run.font.size      = Pt(20)

    sub = doc.add_heading(meeting_title, level=2)
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in sub.runs:
        run.font.color.rgb = RGBColor(21, 101, 192)

    doc.add_paragraph()

    # Summary
    summary = mom_data.get("summary", "")
    if summary:
        h = doc.add_heading("Summary", level=2)
        for run in h.runs:
            run.font.color.rgb = RGBColor(13, 43, 110)
        doc.add_paragraph(summary)
        doc.add_paragraph()

    # Key Discussions
    discussions = mom_data.get("key_discussions", [])
    if discussions:
        h = doc.add_heading("Key Discussions", level=2)
        for run in h.runs:
            run.font.color.rgb = RGBColor(13, 43, 110)
        for d in discussions:
            p    = doc.add_paragraph(style="List Bullet")
            run1 = p.add_run(f"{d.get('topic', '')}: ")
            run1.bold = True
            p.add_run(d.get("details", ""))
        doc.add_paragraph()

    # Decisions
    decisions = mom_data.get("decisions", [])
    if decisions:
        h = doc.add_heading("Decisions Made", level=2)
        for run in h.runs:
            run.font.color.rgb = RGBColor(13, 43, 110)
        for i, d in enumerate(decisions, 1):
            p    = doc.add_paragraph()
            run1 = p.add_run(f"{i}. {d.get('decision', '')}")
            run1.bold = True
            if d.get("reason"):
                p.add_run(f" — {d.get('reason', '')}")
        doc.add_paragraph()

    # Action Items Table
    action_items = mom_data.get("action_items", [])
    if action_items:
        h = doc.add_heading("Action Items", level=2)
        for run in h.runs:
            run.font.color.rgb = RGBColor(13, 43, 110)

        table = doc.add_table(rows=1, cols=4)
        table.style = "Table Grid"

        headers = ["Task", "Assigned To", "Deadline", "Priority"]
        hdr_cells = table.rows[0].cells
        for i, hdr in enumerate(headers):
            hdr_cells[i].text = hdr
            run = hdr_cells[i].paragraphs[0].runs[0]
            run.bold = True
            run.font.color.rgb = RGBColor(255, 255, 255)
            set_cell_bg(hdr_cells[i], "0D2B6E")

        for item in action_items:
            row = table.add_row()
            row.cells[0].text = item.get("task", "")
            row.cells[1].text = item.get("assigned_to", "TBD")
            row.cells[2].text = item.get("deadline", "TBD")
            row.cells[3].text = item.get(
                "priority", "medium"
            ).upper()

        doc.add_paragraph()

    # Next Meeting
    next_meeting = mom_data.get("next_meeting", "")
    if next_meeting and next_meeting != "N/A":
        h = doc.add_heading("Next Meeting", level=2)
        for run in h.runs:
            run.font.color.rgb = RGBColor(13, 43, 110)
        doc.add_paragraph(next_meeting)
        doc.add_paragraph()

    # Footer
    footer_p           = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run                = footer_p.add_run(
        "Generated by AI Meeting Platform"
    )
    run.font.color.rgb = RGBColor(100, 100, 100)
    run.font.size      = Pt(9)
    run.italic         = True

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()